### ISSUE TITLE
auto-add TTS staff to Slack

### ISSUE THREAD

**Issue by afeld** [GSA-TTS/tts-tech-operations#1178]
## Background Information

[From Slack:](https://gsa-tts.slack.com/archives/C01CVRM54S2/p1610586438000300?thread_ts=1610580324.023500&cid=C01CVRM54S2)

> Users could also be [automatically added to their relevant workspace based on their identify provider group](https://slack.com/help/articles/115001435788-Connect-identity-provider-groups-to-your-Enterprise-Grid-org)... so that when they joined the GSA Enterprise they would already be assigned to the relevant workspace(s).

This would take away the manual invitation steps for new TTS staff.

## Implementation Steps
- [ ] 

## Acceptance Criteria

- [ ] TTS staff are automatically added as full members to the TTS workspace when they onboard

**Comment by JJediny** [comment]
Done
