### ISSUE TITLE
review site redesign process

### ISSUE THREAD

**Issue by afeld** [GSA-TTS/tts-tech-operations#1205]
## Background Information

Asked to review the [process doc for site redesigns](https://docs.google.com/document/d/1saLHjVKj1AtKlZggyOOT27uIOQsfqu388aXxkjiJZi8/edit) from the Digital Council. Also asked to consider what review should be required for redesigns/rebuilds, which we'll develop as a separate task: https://github.com/18F/tts-tech-portfolio/issues/1169

## Implementation Steps
- [ ] Read doc
- [ ] Leave comments
- [ ] Notify Council

## Acceptance Criteria

- [ ] Tech Portfolio consensus on redesign process

**Comment by afeld** [comment]
See also: [review process for new sites](https://docs.google.com/document/d/1j6eieL3oop0rxCAldVVh7uGdOCG-ajafrog_BZ-u470/edit).

**Comment by JJediny** [comment]
Need to determine if this is still needed by coordinating with :

- [ ] DLP
- [ ] Touchpoints
- [ ] Quartly Content Review 
- [ ] GSA PAges
