### ISSUE TITLE
Explore improving the public channel experience

### ISSUE THREAD

**Issue by its-a-lisa-at-work** [GSA-TTS/tts-tech-operations#1242]
Background: 
[Slack conversation about signing in limits](https://gsa-tts.slack.com/archives/C039MHHF8/p1613144720071000)
[Slack conversation about converging certain channels](https://gsa-tts.slack.com/archives/C02KW46DP/p1611672037046000)

**Comment by pburkholder** [comment]
From #discuss-tts-public-slack :

> TTS used to be the home to thriving communities in our public slack channels listed at https://chat.18f.gov, but those have all largely died since we required external users to reauthenticate after 12 hours using MFA.
We would like to revive interactions in our communities of practice, and Slack would be a great way to do so, but we'd need a re-authentication policy that better matches the risk associated with public channels and single-channel guests.

I've learned that the only way technically to support public Slack channels is to create a new Slack (say, tts-public.slack.com) and authorize it Low Impact with AAL1 identity requirements, so reauthentication is only needed every 30 days.

**Comment by pburkholder** [comment]
More context:

[Have all our public slack channels died... (March 2022)](https://gsa-tts.slack.com/archives/C04KL9ZN2/p1648479799098119)

[

[Inspired by this slack thread (April 2022)](https://gsa-tts.slack.com/archives/C05693VM7/p1649793065492109), an idea that just occurred to me would be to spin up a paid slack org for communities of practice that could, among other things serve as a new home for our -public channels that would not require people to auth daily

**Comment by JJediny** [comment]
Closing as no work identified to complete
