### ISSUE TITLE
C-SCRM Champion

### ISSUE THREAD

**Issue by JJediny** [GSA-TTS/tts-tech-operations#1683]
5/16 C-SCRM Update - https://docs.google.com/document/d/1UJLDeKzCpYMFnTeraMkY4Fvb_uq7g859EfgXZwg5j90/edit

**Comment by MichaelSides** [comment]
Held knowledge transfer sessions with @rocheller123 and was added to the C-SCRM Monthly Meetings https://calendar.google.com/calendar/r?eid=ZmszNGtlbTdyNWowN25hdmpoMmRxNzhxZDJfUjIwMjQwNjA2VDE1MDAwMCBtaWNoYWVsLnNpZGVzQGdzYS5nb3Y&ctok=bWljaGFlbC5zaWRlc0Bnc2EuZ292

**Comment by MichaelSides** [comment]
C-SCRM vendor attestation/checklist template:  https://docs.google.com/spreadsheets/d/150Drz2BfXqTK5oEuGgZzGiVw0Gvq0JNu/edit?usp=drive_link&ouid=112264215005798534410&rtpof=true&sd=true 

Not applicable to an LiSaaS?

**Comment by MichaelSides** [comment]
On tap for week of 5/20-24:

1. Continue knowledge transfer sessions with Rochelle

**Comment by MichaelSides** [comment]
Validated with Rochelle that all knowledge has been transferred, will begin functioning as the TTS Tech Ops C-SCRM Champ.
