### ISSUE TITLE
Yello ATO

### ISSUE THREAD

**Issue by MichaelSides** [GSA-TTS/tts-tech-operations#1693]
Support OCISO on renewing the Yello XaaS ATO

**Comment by MichaelSides** [comment]
- [ ] Mary and Mike develop support strategy
- [ ] Schedule internal TTS Tech Ops meeting with Ethan 
- [ ] Schedule regular sync meetings with SO and ISSO/ISSM

**Comment by JJediny** [comment]
@Mgilesd reviewed SSPP for the control implementations and validated status 6/11

**Comment by MichaelSides** [comment]
Email from ISSM/Sergio on Weds, June 26:

Hey Chris and team, 
Based on our call today it seemed as though we are attempting to write to an environment that has not yet been completely set up and configured in a way that it will be operating in prod. If that is the case then the assessment will need to be delayed further until such milestones have been completed and the documentation has been updated to accurately reflect how the controls have been implemented.

**Comment by MichaelSides** [comment]
6/27:  Had a conversation with Sergio/ISSM on the current blocker -- our collective understanding that the Yello prod environment is NOT configured and therefore NOT ready to be assessed.  USDC System Owner just gained admin level access into the service and would be unable to provide screenshots/evidence of compliance for the SSP/CRM controls.

Potential Options and Feasibility:

1) IATT/Authority to Test.  Not feasible as this is a prod instance with large amounts of PII.
2) ATO-C/Conditional ATO:  Not feasible with the large amounts of PII and inherent risk of all CRM/customer controls being non-compliant at this point.  Residual Risk would be HIGH.
3) Type Accreditation/Authorization:  Not feasible as this is a MiSaaS and not a full ATO package and cannot do a type accreditation on a CRM.

Will setup a meeting with @Mgilesd, @ethanheppner, and LaKeisha Russell on Monday, July 1st to discuss path forward.

**Comment by MichaelSides** [comment]
July 2, 2024 Meeting Notes/Highlights:

1. @ethanheppner clarified that a production instance is available to USDC, based on their requirements from Jan/Feb timeframe.  This needs to be re-visited/re-validated. 
2. @Sergioajimenez clarified that his major concern is a knowledge gap with USDC System Owners that is impacting the ATO timeline.  SSPP test results are insufficient.
3. - LaKeisha would like Tech Ops to retain SO responsibilities for now, until ATO is achieved and then handoff to USDC, in order to facilitate ATO award ASAP.

Action Items for Week of 7/8/24:
- [ ] Sergio and Jonathan will review and comment on the SSPP, but primary issue is that many of the test results do not address current configuration/compliance status (instead of the "future" state) or enough detail to properly assess.
- [ ] @ethanheppner @Mgilesd @MichaelSides to review SSPP and identify where control test results can be updated
- [ ] Sergio and Jonathan to work PTA/PIA
- [ ] LaKeisha will setup a meeting between Tech Ops and USDC to outline the path forward

**Comment by MichaelSides** [comment]
Meeting on 7/8/24 between LaKeisha/Tech Ops and USDC to outline path forward.  Due to the high priority and implications of not obtaining an ATO prior to end of Aug:  Tech Ops, Mike/Mary/Ethan, will assist in cleaning up the Yello SSP.  Mike scheduled daily sync sessions for next two weeks.

**Comment by MichaelSides** [comment]
7/10/24:  Review and update of SSP continued, based on comments and recommendations from Tech Ops and ISSO.

Pushing to finish out the update on 7/11/24.

**Comment by MichaelSides** [comment]
7/15/24:  ATO Package officially submitted.  

Tech Ops is standing by, ready to provide additional support as needed.

**Comment by MichaelSides** [comment]
7/16/24:

Notified by ISSM that 29 additional privacy controls will need to be added to the SSP.  ISSO is adding and we will spin up assessment sessions ASAP.

**Comment by MichaelSides** [comment]
7/25:  Met with Sergio/ISSM and current status:

1. PTA is approved
2. PIA is now in the ISSO/ISSM queue
3. Sergio will get with Jonathan to look at the PIA
4. Sergio will also inquire about an "expedited ATO" request/path

7/26:  Jonathan/ISSO sent out the PIA, requesting input.  I've setup a meeting at lunch today to answer questions and finalize PIA.

**Comment by MichaelSides** [comment]
- PTA is officially in Archer
- Jackie is reviewing the PIA
- All of the privacy controls were added in the SSPP
- Assessment is schedule for Aug 5th
- Sergio believes we are in a good spot

**Comment by MichaelSides** [comment]
Reopened.

Tech Ops is supporting USDC/System Owner during demo/walkthroughs for RMF control validators week of 8/5.  

- [ ] Part I 8/5
- [ ] Part II 8/6
- [ ] Part III ?

**Comment by MichaelSides** [comment]
8/12/24:

PIA discussions are still ongoing between Privacy Office, ISSO/ISSM and USDC System Owner.  No tasks for Tech Ops.

Artifact requests are still pending with USDC System Owner (onboarding/offboarding and change request email) and GSA IT SSO (SecureAuth Config screenshot).  No tasks for Tech Ops.

Tech Ops is standing by, ready to continue support as needed/requested.
