### ISSUE TITLE
GSA Pages - Contingency Plan Test Report

### ISSUE THREAD

**Issue by JJediny** [GSA-TTS/tts-tech-operations#1695]
- [x] Develop a Test Scenario based on [CP Plan](https://docs.google.com/document/d/1gezf3cUsaBU4d4YA_Q7HijXXFRbOjpUFomez1_e2V40/edit?usp=drive_link)
- [x] Upload [Test Report](https://drive.google.com/drive/folders/1EUTPhVxZ97Iv8-GdHURBAtdv2I5VLJ7G?usp=drive_link)

## Templates
https://insite.gsa.gov/system/files/insite/Information_System_Contingency_Plan_Test_Plan_Template_07-28-2020.docx
https://insite.gsa.gov/system/files/insite/Information_System_Contingency_Plan_Test_Report_Template_07-28-2020.docx

**Comment by MichaelSides** [comment]
7/30/24:

@MichaelSides @Mgilesd added comments to the TTX template:  https://docs.google.com/document/d/15A9sur65yn0qoizIT3maAs_F7levZ_oD/edit?usp=comment_email_document&ts=66aa2ea7&usp_dm=false 

- [ ] Finalize ISCP TTX test plan
- [ ] Schedule TTX
- [ ] Perform TTX
- [ ] Finalize TTX AAR

**Comment by JJediny** [comment]
Email sent to share document for ISSO review. @Mgilesd to setup meeting with ISSO @JJediny to provide test websites participates

**Comment by MichaelSides** [comment]
8/8/24:  Tech Ops met with ISSO/Sue.  BIA, ISCP, CP Test Plan and Test Report all need to be updated and finalized. 

Action items:

- [ ] @MichaelSides to update BIA https://docs.google.com/document/d/1nMCdccfozbruCN1qQc-_QuQq1R9xe4wBOCMSOb9k7T8/edit 
- [ ] @Mgilesd to update ISCP https://docs.google.com/document/d/1NATznE4eNhWXyW-xXUpn5cDumRFDy-7lJowRaCoHe9g/edit
- [ ] @JJediny to update CP TTX Test Plan https://docs.google.com/document/d/1Rnx5HDTkWkR76j_Ermnnq7IQYe0yDoNcl4QgxMnPDg4/edit
- [ ] AAR will need to wait until after the TTX

**Comment by MichaelSides** [comment]
All documentation has gone final in https://drive.google.com/drive/folders/1XhriiHNbWC2sWMoTfmAFPtnMkPSy3WHd 

ISSO is moving everything, to include the BIA, ISCP, Test Plan, TTX Meeting Notes and AAR/Test Report over to Archer and closing out the associated POAM.

Closing this task, as Tech Ops work is complete.
