### ISSUE TITLE
GSA Pages - ATU Review Workflow Recording

### ISSUE THREAD

**Issue by JJediny** [GSA-TTS/tts-tech-operations#1706]
## Acceptance Criteria

- [x] Use Github to document [Web Manager Training Attestation](https://github.com/GSA-TTS/gsa-pages/blob/main/.github/ISSUE_TEMPLATE/ATU.yml)
  - [ ] Document Screenshot workflow through Github Repository
  - [ ] Document Github Membership transfer from [GSA Pages - Tenant Status](https://docs.google.com/spreadsheets/d/1ShQTaffezxJ-MLdc71ctdwBdRkz4NGRhZ0EqmhJWJng/edit#gid=0)
- [ ] Transposing Spreadsheet/Github Issue into ATU Word Document template
- [ ] Routing the ATU letter via Docusign

**Comment by JJediny** [comment]
Recording today 6/20

**Comment by MichaelSides** [comment]
@Mgilesd working on ATU forms.  Sample here:  https://docs.google.com/document/d/1Hd55esq2QWtGJAuOpq_gb9rIzehcj-YeQEFB62M4KEI/edit

**Comment by JJediny** [comment]
Closing until we finish the formal DOCX routing. WIll reopen
