### ISSUE TITLE
Coordinate and Finalize TTS SOC Decision Memo 

### ISSUE THREAD

**Issue by MichaelSides** [GSA-TTS/tts-tech-operations#1719]
https://docs.google.com/document/d/1YVGl_jqQ-pWdqhvXbeRqLmgXFyk5Zvx0MdlF1rdpVho/edit

- [x] Get Anne's questions answered
- [x] Collect Pros and Cons
- [ ] Coordinate final submission of TTS decision memo

**Comment by MichaelSides** [comment]
Awaiting TTS system input on Decision Memo and Matrix.  Awaiting requested feedback from Login.gov on their perceived gaps/deficiencies.

SOC maturity levels do not appear to be defined in federal guidance/regs.  The best we can do is to match up the NIST 800-53 controls to the normal SOC functions and use those as the baseline requirements, equiv to:

https://docs.google.com/spreadsheets/d/1CCGa-YAGhm99bElJ1PKl2WVw5gTLil8C/edit?usp=drive_link&ouid=112264215005798534410&rtpof=true&sd=true 

With 2 caveats/conditions:  1) This maps typical SOC functions/services to 800-53 rev4.  Since GSA (and TTS) is a mixed/hybrid rev4/5 environment at the moment (due to FedRAMP restrictions), a rev 5 mapping will also need to be accomplished.  and 2) The appropriate CIA levels will need to be taken into account (ie not all controls will be applicable to all TTS systems).

**Comment by MichaelSides** [comment]
Week of 7/8/24:

- [ ] Continue to support final edits to the SOCaaS TTS Decision Memo

**Comment by MichaelSides** [comment]
Final Memo:  https://docs.google.com/document/d/1bDYWVGRODxKb6EOS6ToCLPAnR1q5dZYURrd1D9hlZpc/edit?usp=sharing_eil_se_dm&ts=668e9006

BLUF:  TTS will be compliant IAW the M-21-31 CAP NLT 9/30/25.  TTS programs will determine the best path to M-21-31 compliance based on program needs, integration concerns, and maturity and architecture of available SOC products. 

No further action required from Tech Ops.  Phase 1 M-21-31 Tracking:  https://github.com/GSA-TTS/tts-tech-operations/issues/1555 

Closing this issue/project.

**Comment by JJediny** [comment]
- [ ] Tech Operations access to SoCaaS SSPP and CRM Documentation

**Comment by JJediny** [comment]
Closing as the Memo is finalized action items being tracked:
https://github.com/GSA-TTS/tts-tech-operations/issues/1723
https://github.com/GSA-TTS/tts-tech-operations/issues/1558
