### ISSUE TITLE
Review Github Organizational Role Assignments and Least Privilege Concerns

### ISSUE THREAD

**Issue by JJediny** [GSA-TTS/tts-tech-operations#1780]
Ref request https://gsa-tts.slack.com/archives/C02KXM98G/p1727884583337059

BLUF:  Greg Walker requested to modify the 18F org so that all repos give the @18f-engineers team write access by default, and the @18f-engineering-leadership team has admin access by default.  Actions taken:   Granted the engineers team write access by default.  However, in accordance with our least privilege model, we only granted the leadership team with "maintainer" default access for now.  See thread above for list of concerns.

Greg is good with this for now but leadership team privs might need to be adjusted.

**Comment by MichaelSides** [comment]
10/8/24:  Now that all orgs are rolled up under the GSA Enterprise, this is a good time to review.
