### ISSUE TITLE
ensure projects are being handed off to partners

### ISSUE THREAD

**Issue by afeld** [GSA-TTS/tts-tech-operations#308]
## Background information

When partner projects end, TTS needs to ensure various things happen:

- Repositories are transferred or archived
- TTS is no longer paying for any infrastructure
- TTS is no longer paying for of the contact on domain name registrations
- The site is no longer using TTS DNS
- ...

This applies to both handoff (the partner is continuing with the project) and [decommissioning](https://before-you-ship.18f.gov/infrastructure/decommissioning/) (the project is being shut down).

## User stories

- As a member of the Tech Portfolio, I don't want to be responsible for code/costs/risks that are no longer TTS's responsibility so that they don't take our time/money down the road.
- As a TTS partner, I want to ensure I have control of all resources related to my project so that I can continue it (or not) as I choose.

## Implementation

- [ ] Think through all the things that need to happen (build on list above)
- [ ] Decide/determine canonical documentation for project handoff
- [ ] Reconcile with various existing documentation
   - [Decommissioning](https://before-you-ship.18f.gov/infrastructure/decommissioning/)
   - Various Handbook pages, such as [archiving GitHub repositories](https://handbook.18f.gov/github/#archiving)
- [ ] Review by PIF
- [ ] Review by CoEs
- [ ] Review by 18F

## Acceptance criteria

- List of project handoff steps is documented

## Relevant links

- [Slack conversation](https://gsa-tts.slack.com/archives/CHZLJBWCV/p1578325492056800)

**Comment by its-a-lisa-at-work** [comment]
Mind if we keep this in the Backlog? I think things that are already Sprint Planned for shouldn't go back into Icebox so they stay as something that gets picked up as soon as possible.

**Comment by afeld** [comment]
[18F Project Closeout Checklist](https://docs.google.com/document/d/1AnY9XJWHABoKgJfmuP8IKccbeNt-P8YXi0FbMVZQFjw/edit?ts=60c14830) from @hannahkane, which seems like the thing to build from. @keithpif @adam-grandt-tts would you be ok with adopting that checklist for PIF and COEs, respectively?

**Comment by JJediny** [comment]
Determined with team that these orgs should document their own project transferring process
