### ISSUE TITLE
automate creation of recurring tasks

### ISSUE THREAD

**Issue by afeld** [GSA-TTS/tts-tech-operations#882]
## Background information

We have a couple recurring tasks that we sometimes forget to get onto the board:

- [ ] OpsRotation
- [x] Invoices for COR - https://github.com/18F/tts-tech-portfolio/pull/1488
   - AWS
   - HackerOne
   - GCP
   - Mural
   - New Relic
   - Azure
   - …
- [ ] HackerOne catch-up
- [ ] POAM review
- [ ] Software Concierge / SaaS stuff

Would be helpful to automate this, since it's otherwise easy to forget them during Sprint Planning or whatnot.

## Acceptance criteria

- Issues are automatically created for the recurring tasks listed above

---

The assignee can add some checkboxes as a "sketch" of the steps to complete, which may evolve.

**Comment by adborden** [comment]
Has there been any thought on implementation? GH actions are very powerful for creating GH-based workflows. 

You could tie Sprints to GH Releases/Milestones and autogenerate a release from issues closed in the sprint. That's probably half of your SMT report there (sprint release notes).

Using the same idea, you could hook into OpsRotation issues to creation of milestones or other issues (create one and the others are generated automatically).

**Comment by afeld** [comment]
All sounds great!
