### ISSUE TITLE
Inspector posting to public channels

### ISSUE THREAD

**Issue by afeld** [GSA-TTS/tts-tech-operations#948]
## Background Information

There's logic that should prevent this from happening:

https://github.com/18F/tts-tech-portfolio/blob/c36975b7136248cc3b9f1ab7c5ad159034a9aec1/inspector/pr-nudges.js#L63-L64

but that doesn't seem to have prevented [a message getting posted to #identity-public](https://gsa-tts.slack.com/archives/C0ZMH8ZA9/p1604328846013400).

## Implementation Steps
- [ ] 

## Acceptance Criteria

- [ ] A dry run shows no messages being posted to `-public` channels

**Comment by afeijoo** [comment]
A message was posted to #uswds-public on Saturday.

**Comment by afeijoo** [comment]
A message was posted to #uswds-public on Saturday.

**Comment by its-a-lisa-at-work** [comment]
I looked into this a little bit over the weekend and[ took notes](https://github.com/18F/tts-tech-portfolio/pull/1190/commits/5521be4dafd714c1bdb988dd9ae49b84103be245); going to take my name off of it for now and move it out of `In Progress` and let someone else take a shot at it
